### PR TITLE
EE3 support, submodule support

### PR DESCRIPTION
**Pull request by meatpaste**
Move files into root folder so repo can be added as a submodule.
Update to support EE3 while maintaining EE2 support.
Load in readme file, DRY

### CODE REVIEW

**Comment by wesbaker** [comment]
We'd be happy for the EE3 support, but the submodule support defeats a lot of the build automation we've been adding to our other add-ons. (Take a look at [EllisLab/Cron](https://github.com/EllisLab/Cron) for an example.) So we can't accept the pull request with the submodule support in it. If you want to undo that part of it, I'd be happy to accept the pull request.

**Comment by meatpaste** [comment]
Cheers, would having the readme in the subfolder fit your requirements so that the plugin file can read it in?

**Comment by wesbaker** [comment]
The README.md needs to be at the same levels the addon files. You can move it around as long as there's a symlink there.

**Comment by wesbaker** [comment]
@robinsowell could I ask you to close this PR? I don't think it's getting merged any time soon 😆 and I was just cleaning up my PRs.

**Comment by robinsowell** [comment]
HEE!!  And done!

**Pull request closed without merging**
