### PR TITLE
Added option to force elipses for exact trimmed strings

### PR DESCRIPTION
**Pull request by nathanpitman**

### CODE REVIEW

**Comment by kevincupp** [comment]
Hi Nathan, thanks for this. Looks good, but could you fix a couple things?

- [ ] Fix spelling of "elipses" to "ellipses"
- [ ] Follow our [guidelines on indenting and bracing](https://ellislab.com/expressionengine/user-guide/development/guidelines/general.html#code-indenting), I know it's not consistently done in this file but we're trying to encourage a uniform style

**Comment by nathanpitman** [comment]
Hi Kevin, lol on the spelling - will fix that, along with the indenting and bracing. Thanks for taking a look at this. :)

**Comment by nathanpitman** [comment]
Ok, try that...

**Comment by kevincupp** [comment]
Thanks, Nathan! Looks good, got it merged in. Thanks for your contribution!

**Pull request merged**
